[project]
name = "room-light-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi-mcp>=0.4.0",
    "fastapi[standard]>=0.118.0",
    "ipykernel>=6.30.1",
]
